languageCode = "en"
languageName = "English"
weight = 1
title = "Firdaus.ai"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Firdaus.ai"
image = "profile-picture.jpg"
headline = "I share my tech projects, AI learning journey, and the lessons I pick up along the way"
bio = "Coding wizard by day (and night), cat-wrangler by night (and day), I'm a Ph.D. student in health informatics with interest in software engineering, entrepreneurship, and AI. Join me on this non caffeinated-fueled journey – now with 100% more cat hair!"
links = [
    { twitter = "https://twitter.com/firdausai" },
    { github = "https://github.com/firdausai" },
]